export type Ders = { id: number; adi: string; aciklama: string; modul: string; youtubeUrl: string };

export const M15 = "MODÜL 15- Bibliyometrik Veri Analizi Eğitimi";
export const M14 = "Modül 14 — Veri Kazıma ve Metin Madenciliği";
export const M12 = "MODÜL 12 — Graphical Abstract Eğitimi";
export const M7  = "MODÜL 7 — Kategorik Veri Analizi";
export const M6  = "MODÜL 6 — Meta Analizi Eğitimi";
export const M5  = "MODÜL 5 — Microsoft Office ve EndNote";
export const M4  = "MODÜL 4 — G*Power ile Güç Analizi";
export const M3  = "MODÜL 3 — Ölçek Geliştirme ve YEM";
export const M2  = "MODÜL 2 — İleri Düzey Veri Analizi";
export const M1  = "MODÜL 1 — Temel Düzey Veri Analizi";

export const lessons: Ders[] = [
  { id: 164, adi: "VOS21. Makale Performansı",                                          aciklama: "", modul: M15, youtubeUrl: "https://www.youtube.com/watch?v=bvKNE18FSds" },
  { id: 163, adi: "VOS20. Anahtar Kelime Analizi",                                      aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 162, adi: "VOS19. VOSviewer Görsellerini Kaydetme ya da Kopyalama",             aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 161, adi: "VOS18. En Potansiyelli Yazarları Bulma",                             aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 160, adi: "VOS17. En İşbirlikçi Yazarları Bulma",                               aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 159, adi: "VOS16. En Güncel Yayınlara Sahip Yazarları Bulma",                  aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 158, adi: "VOS15. En Üretken Yazarları Bulma",                                  aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 157, adi: "VOS14. En Etkili Yazarları Bulma",                                   aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 156, adi: "VOS13. Sonuçları Dışa Aktarma ve Excel Üzerinde İşlem Yapma",       aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 155, adi: "VOS12. Normalizasyon Yöntemleri",                                    aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 154, adi: "VOS11. Ortak Atıf Analizi",                                          aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 153, adi: "VOS10. Bibliyografik Eşleştirme",                                    aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 152, adi: "VOS9. Ortak Yazarlık Analizi",                                       aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 151, adi: "VOS8. Kümeleme Yöntemleri",                                          aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 150, adi: "VOS7. Görselleştirme Türleri",                                       aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 149, adi: "VOS6. Web of Science'dan Veri Aktarma",                              aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 148, adi: "VOS5. Scopus'tan Veri Aktarma",                                      aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 147, adi: "VOS4. VOSviewer Arayüzüne Giriş",                                   aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 146, adi: "VOS3. Bibliyometri Nedir?",                                          aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 145, adi: "VOS2. VOSviewer Kurulumu",                                           aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 144, adi: "VOS1. Bibliyometrik Analize Giriş",                                  aciklama: "", modul: M15, youtubeUrl: "" },
  { id: 143, adi: "GA8. Şekil Kaydı ve Gönderim Formatları",                            aciklama: "", modul: M12, youtubeUrl: "" },
  { id: 142, adi: "GA7. Renk Teorisi ve Paletler",                                      aciklama: "", modul: M12, youtubeUrl: "" },
  { id: 141, adi: "GA6. İnfografik Tasarımı",                                           aciklama: "", modul: M12, youtubeUrl: "" },
  { id: 140, adi: "GA5. BioRender Kullanımı",                                           aciklama: "", modul: M12, youtubeUrl: "" },
  { id: 139, adi: "GA4. Canva ile Graphical Abstract",                                  aciklama: "", modul: M12, youtubeUrl: "" },
  { id: 138, adi: "GA3. Graphical Abstract Örnekleri",                                  aciklama: "", modul: M12, youtubeUrl: "" },
  { id: 137, adi: "GA2. Dergi Gereksinimleri",                                          aciklama: "", modul: M12, youtubeUrl: "" },
  { id: 136, adi: "GA1. Graphical Abstract Nedir?",                                     aciklama: "", modul: M12, youtubeUrl: "" },
  { id: 135, adi: "KV12. Lojistik Regresyon Yorumlama",                                 aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 134, adi: "KV11. Lojistik Regresyon Analizi",                                   aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 133, adi: "KV10. Ki-kare Bağımsızlık Testi",                                    aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 132, adi: "KV9. Ki-kare Uyum İyiliği Testi",                                    aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 131, adi: "KV8. Çapraz Tablolar ve Göreceli Risk",                              aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 130, adi: "KV7. Nominal Ölçek Analizi",                                         aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 129, adi: "KV6. Ordinal Veri Analizi",                                          aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 128, adi: "KV5. Kategorik Değişkenler",                                         aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 127, adi: "KV4. Frekans Tabloları",                                             aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 126, adi: "KV3. Veri Kodlama",                                                  aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 125, adi: "KV2. SPSS'te Kategorik Veri Girişi",                                 aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 124, adi: "KV1. Kategorik Veriye Giriş",                                        aciklama: "", modul: M7,  youtubeUrl: "" },
  { id: 123, adi: "META12. Meta-Analiz Raporu Yazımı",                                  aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 122, adi: "META11. Yayın Yanlılığı Testleri",                                   aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 121, adi: "META10. Forest Plot Yorumlama",                                       aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 120, adi: "META9. Heterojenlik Analizi",                                         aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 119, adi: "META8. Sabit ve Rastgele Etkiler Modeli",                            aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 118, adi: "META7. Etki Büyüklüğü Hesaplama",                                    aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 117, adi: "META6. Sistematik Literatür Tarama",                                  aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 116, adi: "META5. PRISMA Akış Diagramı",                                        aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 115, adi: "META4. Meta-Analiz Yazılımları",                                     aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 114, adi: "META3. Veri Kodlama Formu",                                          aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 113, adi: "META2. Dahil Etme ve Dışlama Kriterleri",                            aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 112, adi: "META1. Meta-Analize Giriş",                                          aciklama: "", modul: M6,  youtubeUrl: "" },
  { id: 111, adi: "YEM15. YEM Raporlama",                                               aciklama: "", modul: M3,  youtubeUrl: "" },
  { id: 110, adi: "YEM14. Yapısal Model Değerlendirme",                                 aciklama: "", modul: M3,  youtubeUrl: "" },
  { id: 109, adi: "YEM13. Ölçüm Modeli",                                                aciklama: "", modul: M3,  youtubeUrl: "" },
  { id: 108, adi: "YEM12. Doğrulayıcı Faktör Analizi",                                  aciklama: "", modul: M3,  youtubeUrl: "" },
  { id: 107, adi: "YEM11. Açıklayıcı Faktör Analizi",                                   aciklama: "", modul: M3,  youtubeUrl: "" },
  { id: 106, adi: "YEM10. Ölçek Güvenilirliği",                                         aciklama: "", modul: M3,  youtubeUrl: "" },
  { id: 105, adi: "YEM9. Ölçek Geçerliliği",                                            aciklama: "", modul: M3,  youtubeUrl: "" },
  { id: 104, adi: "GP8. G*Power Çoklu Regresyon",                                       aciklama: "", modul: M4,  youtubeUrl: "" },
  { id: 103, adi: "GP7. G*Power MANOVA Güç",                                            aciklama: "", modul: M4,  youtubeUrl: "" },
  { id: 102, adi: "GP6. G*Power ANOVA Güç Analizi",                                     aciklama: "", modul: M4,  youtubeUrl: "" },
  { id: 101, adi: "GP5. G*Power Korelasyon Güç",                                        aciklama: "", modul: M4,  youtubeUrl: "" },
  { id: 100, adi: "GP4. G*Power t-testi Güç",                                           aciklama: "", modul: M4,  youtubeUrl: "" },
  { id: 99,  adi: "GP3. Etki Büyüklüğü Ölçüleri",                                      aciklama: "", modul: M4,  youtubeUrl: "" },
  { id: 98,  adi: "GP2. G*Power Kurulumu ve Arayüz",                                    aciklama: "", modul: M4,  youtubeUrl: "" },
  { id: 97,  adi: "GP1. Güç Analizine Giriş",                                           aciklama: "", modul: M4,  youtubeUrl: "" },
  { id: 96,  adi: "ID20. İleri Regresyon Analizi",                                      aciklama: "", modul: M2,  youtubeUrl: "" },
  { id: 95,  adi: "ID19. Hiyerarşik Regresyon",                                         aciklama: "", modul: M2,  youtubeUrl: "" },
  { id: 94,  adi: "ID18. MANOVA",                                                       aciklama: "", modul: M2,  youtubeUrl: "" },
  { id: 93,  adi: "ID17. ANCOVA",                                                       aciklama: "", modul: M2,  youtubeUrl: "" },
  { id: 92,  adi: "ID16. İki Yönlü ANOVA",                                              aciklama: "", modul: M2,  youtubeUrl: "" },
  { id: 91,  adi: "TD15. Tek Örneklem t-testi",                                         aciklama: "", modul: M1,  youtubeUrl: "" },
  { id: 90,  adi: "TD14. Mann-Whitney U Testi",                                          aciklama: "", modul: M1,  youtubeUrl: "" },
  { id: 89,  adi: "TD13. Bağımsız Örneklem t-testi",                                    aciklama: "", modul: M1,  youtubeUrl: "" },
  { id: 88,  adi: "TD12. Normallik Testleri",                                            aciklama: "", modul: M1,  youtubeUrl: "" },
  { id: 87,  adi: "TD11. Merkezi Eğilim ve Dağılım Ölçüleri",                           aciklama: "", modul: M1,  youtubeUrl: "" },
  { id: 86,  adi: "TD10. Frekans ve Yüzde Tablolar",                                    aciklama: "", modul: M1,  youtubeUrl: "" },
];
