"use client";

import Link from "next/link";
import { FormEvent, ReactNode, useEffect, useState } from "react";
import { SystemDropdown } from "../../components/SystemDropdown";
import { AdminShell } from "../AdminShell";
import { defaultHomeSettings, HomeSettings, readHomeSettings, writeHomeSettings } from "./homeSettingsData";

type IconName = "home" | "video" | "process" | "education" | "building" | "mail" | "eye" | "faq" | "message" | "save" | "plus" | "trash" | "services";
function Icon({ name,size=17 }:{ name:IconName;size?:number }) {
  const paths:Record<IconName,ReactNode> = {
    home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></>,
    video:<><rect x="3" y="5" width="14" height="14" rx="2"/><path d="m17 10 4-2v8l-4-2"/></>,
    process:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
    education:<><path d="m3 10 9-5 9 5-9 5-9-5Z"/><path d="M7 12v5c3 2 7 2 10 0v-5"/></>,
    building:<><path d="M4 21V5l8-3 8 3v16M9 9h.01M15 9h.01M9 13h.01M15 13h.01M9 17h6"/></>,
    mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></>,
    eye:<><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,
    faq:<><circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 1 1 3.3 2.2c-.8.4-1.1.9-1.1 1.8M12 16h.01"/></>,
    message:<><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/></>,
    save:<><path d="M5 3h12l4 4v14H3V3h2Z"/><path d="M7 3v6h10V3M7 21v-8h10v8"/></>,
    plus:<path d="M12 5v14M5 12h14"/>,trash:<><path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6M10 11v5M14 11v5"/></>,
    services:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function Section({ icon,title,children }:{ icon:IconName;title:string;children:ReactNode }) {
  return <section className="detail-panel home-settings-section"><div className="service-form-section-heading"><span><Icon name={icon}/></span><strong>{title}</strong></div><div className="settings-panel-body">{children}</div></section>;
}
function Field({ label,children }:{ label:string;children:ReactNode }) { return <div className="form-field"><label>{label}</label>{children}</div>; }
const uid = (prefix:string) => `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;

export default function HomeSettingsPage() {
  const [settings,setSettings] = useState<HomeSettings>(defaultHomeSettings);
  const [saved,setSaved] = useState(false);
  useEffect(() => setSettings(readHomeSettings()),[]);
  function commit(event:FormEvent) { event.preventDefault(); writeHomeSettings(settings); setSaved(true); window.setTimeout(() => setSaved(false),2400); }
  const setHero = (key:keyof HomeSettings["hero"],value:string) => setSettings(current => ({...current,hero:{...current.hero,[key]:value}}));
  const setContact = (key:keyof HomeSettings["contact"],value:string) => setSettings(current => ({...current,contact:{...current.contact,[key]:value}}));
  const setCorporate = (key:keyof HomeSettings["corporate"],value:string) => setSettings(current => ({...current,corporate:{...current.corporate,[key]:value}}));

  return <AdminShell><form className="st-page home-settings-page" onSubmit={commit}>
    <header className="orders-hero"><div><h1>Anasayfa Ayarları</h1><p>Landing içeriklerini tek merkezden yönetin.</p></div></header>
    <div className="home-settings-layout">
      <div className="home-settings-stack">
        <Section icon="home" title="Hero bölümü"><div className="form-grid">
          <Field label="Üst başlık / badge"><input value={settings.hero.badge} onChange={e=>setHero("badge",e.target.value)}/></Field>
          <Field label="Ana başlık"><input value={settings.hero.title} onChange={e=>setHero("title",e.target.value)}/></Field>
        </div><Field label="Alt başlık / açıklama"><textarea className="small" value={settings.hero.description} onChange={e=>setHero("description",e.target.value)}/></Field>
        <div className="form-grid"><Field label="Birincil buton metni"><input value={settings.hero.primaryText} onChange={e=>setHero("primaryText",e.target.value)}/></Field><Field label="Birincil buton URL"><input value={settings.hero.primaryUrl} onChange={e=>setHero("primaryUrl",e.target.value)}/></Field><Field label="İkincil buton metni"><input value={settings.hero.secondaryText} onChange={e=>setHero("secondaryText",e.target.value)}/></Field><Field label="İkincil buton URL"><input value={settings.hero.secondaryUrl} onChange={e=>setHero("secondaryUrl",e.target.value)}/></Field></div></Section>

        <Section icon="video" title="Video embed (YouTube)"><Field label="Tanıtım videosu URL"><input value={settings.introVideoUrl} onChange={e=>setSettings(s=>({...s,introVideoUrl:e.target.value}))} placeholder="https://www.youtube.com/watch?v=..."/><p className="settings-hint">YouTube watch, shorts veya embed bağlantısı kullanabilirsiniz.</p></Field></Section>

        <Section icon="process" title="Nasıl çalışır — adımlar"><div className="form-grid"><Field label="Bölüm başlığı"><input value={settings.process.title} onChange={e=>setSettings(s=>({...s,process:{...s.process,title:e.target.value}}))}/></Field><Field label="Bölüm giriş paragrafı"><input value={settings.process.intro} onChange={e=>setSettings(s=>({...s,process:{...s.process,intro:e.target.value}}))}/></Field></div>
          <div className="home-settings-repeat process-repeat">{settings.process.steps.map((step,index)=><div className="home-settings-repeat-row" key={step.id}><span className="repeat-index">{String(index+1).padStart(2,"0")}</span><input value={step.icon} aria-label={`${index+1}. adım ikonu`} onChange={e=>setSettings(s=>({...s,process:{...s.process,steps:s.process.steps.map(x=>x.id===step.id?{...x,icon:e.target.value}:x)}}))}/><input value={step.title} aria-label={`${index+1}. adım başlığı`} onChange={e=>setSettings(s=>({...s,process:{...s.process,steps:s.process.steps.map(x=>x.id===step.id?{...x,title:e.target.value}:x)}}))}/><textarea value={step.description} aria-label={`${index+1}. adım açıklaması`} onChange={e=>setSettings(s=>({...s,process:{...s.process,steps:s.process.steps.map(x=>x.id===step.id?{...x,description:e.target.value}:x)}}))}/><input value={step.videoUrl} placeholder="Video URL (opsiyonel)" aria-label={`${index+1}. adım video URL`} onChange={e=>setSettings(s=>({...s,process:{...s.process,steps:s.process.steps.map(x=>x.id===step.id?{...x,videoUrl:e.target.value}:x)}}))}/><button type="button" className="repeat-delete" onClick={()=>setSettings(s=>({...s,process:{...s.process,steps:s.process.steps.filter(x=>x.id!==step.id)}}))} aria-label={`${step.title} adımını kaldır`}><Icon name="trash"/></button></div>)}</div>
          <button className="home-settings-add" type="button" onClick={()=>setSettings(s=>({...s,process:{...s.process,steps:[...s.process.steps,{id:uid("step"),icon:"circle",title:"Yeni adım",description:"",videoUrl:""}]}}))}><Icon name="plus"/>Adım ekle</button>
        </Section>

        <Section icon="services" title="Hizmetler"><div className="home-settings-linked"><div><strong>Hizmet kartları merkezi olarak yönetiliyor</strong><p>Başlık, açıklama, görsel, teslimat ve fiyat ayarları Hizmet Yönetimi ekranında tutulur.</p></div><Link href="/admin/siparis-turleri">Hizmetleri yönet <span>→</span></Link></div></Section>

        <Section icon="education" title="Bireysel eğitimler"><div className="home-settings-repeat education-repeat">{settings.educations.map((item,index)=><div className="education-editor" key={item.id}><header><strong>Eğitim {index+1}</strong><button type="button" className="repeat-delete" onClick={()=>setSettings(s=>({...s,educations:s.educations.filter(x=>x.id!==item.id)}))} aria-label="Eğitimi kaldır"><Icon name="trash"/></button></header><div className="form-grid"><Field label="Eğitim adı"><input value={item.title} onChange={e=>setSettings(s=>({...s,educations:s.educations.map(x=>x.id===item.id?{...x,title:e.target.value}:x)}))}/></Field><Field label="Format"><SystemDropdown value={item.format} onChange={value=>setSettings(s=>({...s,educations:s.educations.map(x=>x.id===item.id?{...x,format:value}:x)}))} options={[{value:"online",label:"Online"},{value:"yuz-yuze",label:"Yüz yüze"},{value:"hibrit",label:"Hibrit"}]}/></Field><Field label="Süre"><input value={item.duration} onChange={e=>setSettings(s=>({...s,educations:s.educations.map(x=>x.id===item.id?{...x,duration:e.target.value}:x)}))}/></Field><Field label="Düzey"><input value={item.level} onChange={e=>setSettings(s=>({...s,educations:s.educations.map(x=>x.id===item.id?{...x,level:e.target.value}:x)}))}/></Field><Field label="Ücret"><input value={item.price} onChange={e=>setSettings(s=>({...s,educations:s.educations.map(x=>x.id===item.id?{...x,price:e.target.value}:x)}))}/></Field><Field label="Kapak görseli URL"><input value={item.coverUrl} onChange={e=>setSettings(s=>({...s,educations:s.educations.map(x=>x.id===item.id?{...x,coverUrl:e.target.value}:x)}))}/></Field></div><Field label="Açıklama"><textarea className="small" value={item.description} onChange={e=>setSettings(s=>({...s,educations:s.educations.map(x=>x.id===item.id?{...x,description:e.target.value}:x)}))}/></Field></div>)}</div><button className="home-settings-add" type="button" onClick={()=>setSettings(s=>({...s,educations:[...s.educations,{id:uid("education"),title:"Yeni eğitim",format:"online",duration:"",price:"",level:"",coverUrl:"",description:""}]}))}><Icon name="plus"/>Eğitim ekle</button></Section>

        <Section icon="building" title="Kurumsal eğitim sayfası"><Field label="Sayfa başlığı"><input value={settings.corporate.title} onChange={e=>setCorporate("title",e.target.value)}/></Field><Field label="Alt başlık / açıklama"><textarea className="small" value={settings.corporate.description} onChange={e=>setCorporate("description",e.target.value)}/></Field><Field label="Avantajlar (her satır bir madde)"><textarea value={settings.corporate.benefits} onChange={e=>setCorporate("benefits",e.target.value)}/></Field><div className="form-grid"><Field label="Teklif butonu metni"><input value={settings.corporate.buttonText} onChange={e=>setCorporate("buttonText",e.target.value)}/></Field><Field label="Teklif e-posta adresi"><input type="email" value={settings.corporate.email} onChange={e=>setCorporate("email",e.target.value)}/></Field></div></Section>

        <Section icon="mail" title="İletişim bilgileri"><div className="form-grid"><Field label="E-posta"><input type="email" value={settings.contact.email} onChange={e=>setContact("email",e.target.value)}/></Field><Field label="Telefon"><input value={settings.contact.phone} onChange={e=>setContact("phone",e.target.value)}/></Field></div><Field label="Adres"><input value={settings.contact.address} onChange={e=>setContact("address",e.target.value)}/></Field><div className="form-grid"><Field label="Instagram"><input value={settings.contact.instagram} onChange={e=>setContact("instagram",e.target.value)}/></Field><Field label="LinkedIn"><input value={settings.contact.linkedin} onChange={e=>setContact("linkedin",e.target.value)}/></Field><Field label="Twitter / X"><input value={settings.contact.x} onChange={e=>setContact("x",e.target.value)}/></Field><Field label="Facebook"><input value={settings.contact.facebook} onChange={e=>setContact("facebook",e.target.value)}/></Field></div><Field label="Google Business yorum linki"><input value={settings.contact.googleReview} onChange={e=>setContact("googleReview",e.target.value)}/></Field></Section>

        <Section icon="eye" title="Bölüm görünürlüğü"><div className="visibility-list">{([['services','Hizmetler bölümü','Sipariş türleri ve eğitim kartları'],['blog','Blog ve duyurular bölümü','Aktif duyurular landingde gösterilir'],['faq','SSS / FAQ bölümü','Sık sorulan sorular'],['reviews','Müşteri yorumları','Yıldızlı yorumlar ve videolar']] as const).map(([key,title,desc])=><label key={key}><span><strong>{title}</strong><small>{desc}</small></span><input type="checkbox" checked={settings.visibility[key]} onChange={e=>setSettings(s=>({...s,visibility:{...s.visibility,[key]:e.target.checked}}))}/><i/></label>)}</div></Section>

        <Section icon="faq" title="SSS — sık sorulan sorular"><div className="home-settings-repeat faq-repeat">{settings.faqs.map((faq,index)=><div className="home-settings-repeat-row faq-row" key={faq.id}><span className="repeat-index">{index+1}</span><input value={faq.question} aria-label={`${index+1}. soru`} onChange={e=>setSettings(s=>({...s,faqs:s.faqs.map(x=>x.id===faq.id?{...x,question:e.target.value}:x)}))}/><textarea value={faq.answer} aria-label={`${index+1}. cevap`} onChange={e=>setSettings(s=>({...s,faqs:s.faqs.map(x=>x.id===faq.id?{...x,answer:e.target.value}:x)}))}/><button type="button" className="repeat-delete" onClick={()=>setSettings(s=>({...s,faqs:s.faqs.filter(x=>x.id!==faq.id)}))} aria-label="Soruyu kaldır"><Icon name="trash"/></button></div>)}</div><button className="home-settings-add" type="button" onClick={()=>setSettings(s=>({...s,faqs:[...s.faqs,{id:uid("faq"),question:"",answer:""}]}))}><Icon name="plus"/>Soru ekle</button></Section>

        <Section icon="video" title="Yorum videoları (YouTube Shorts)"><div className="home-settings-repeat simple-repeat">{settings.videos.map((video,index)=><div className="home-settings-repeat-row" key={`${video}-${index}`}><span className="repeat-index">{index+1}</span><input value={video} aria-label={`${index+1}. yorum videosu`} onChange={e=>setSettings(s=>({...s,videos:s.videos.map((x,i)=>i===index?e.target.value:x)}))}/><button type="button" className="repeat-delete" onClick={()=>setSettings(s=>({...s,videos:s.videos.filter((_,i)=>i!==index)}))} aria-label="Videoyu kaldır"><Icon name="trash"/></button></div>)}</div><button className="home-settings-add" type="button" onClick={()=>setSettings(s=>({...s,videos:[...s.videos,""]}))}><Icon name="plus"/>Video ekle</button></Section>

        <Section icon="message" title="Müşteri yorumları"><div className="home-settings-repeat review-repeat">{settings.reviews.map((review,index)=><div className="review-editor" key={review.id}><header><strong>Yorum {index+1}</strong><button type="button" className="repeat-delete" onClick={()=>setSettings(s=>({...s,reviews:s.reviews.filter(x=>x.id!==review.id)}))} aria-label="Yorumu kaldır"><Icon name="trash"/></button></header><div className="form-grid"><Field label="Ad soyad"><input value={review.name} onChange={e=>setSettings(s=>({...s,reviews:s.reviews.map(x=>x.id===review.id?{...x,name:e.target.value}:x)}))}/></Field><Field label="Rol"><input value={review.role} onChange={e=>setSettings(s=>({...s,reviews:s.reviews.map(x=>x.id===review.id?{...x,role:e.target.value}:x)}))}/></Field><Field label="Kurum"><input value={review.institution} onChange={e=>setSettings(s=>({...s,reviews:s.reviews.map(x=>x.id===review.id?{...x,institution:e.target.value}:x)}))}/></Field><Field label="Puan"><SystemDropdown value={review.rating} onChange={value=>setSettings(s=>({...s,reviews:s.reviews.map(x=>x.id===review.id?{...x,rating:value}:x)}))} options={[1,2,3,4,5].map(value=>({value:String(value),label:`${value} yıldız`}))}/></Field></div><Field label="Yorum"><textarea className="small" value={review.quote} onChange={e=>setSettings(s=>({...s,reviews:s.reviews.map(x=>x.id===review.id?{...x,quote:e.target.value}:x)}))}/></Field><Field label="Avatar URL (opsiyonel)"><input value={review.avatarUrl} onChange={e=>setSettings(s=>({...s,reviews:s.reviews.map(x=>x.id===review.id?{...x,avatarUrl:e.target.value}:x)}))}/></Field></div>)}</div><button className="home-settings-add" type="button" onClick={()=>setSettings(s=>({...s,reviews:[...s.reviews,{id:uid("review"),name:"",role:"",institution:"",quote:"",rating:"5",avatarUrl:""}]}))}><Icon name="plus"/>Yorum ekle</button></Section>
      </div>

      <aside className="detail-panel home-settings-summary"><div className="home-settings-summary-head"><Icon name="save"/><strong>Kaydet ve önizle</strong></div><p>Değişiklikler kaydedildikten sonra landing önizlemesini açabilirsiniz.</p><dl><div><dt>Bireysel eğitim</dt><dd>{settings.educations.length}</dd></div><div><dt>Adım sayısı</dt><dd>{settings.process.steps.length}</dd></div><div><dt>Müşteri yorumu</dt><dd>{settings.reviews.length}</dd></div><div><dt>SSS soru sayısı</dt><dd>{settings.faqs.length}</dd></div><div><dt>Yorum videosu</dt><dd>{settings.videos.length}</dd></div></dl>{saved&&<span className="home-settings-saved" role="status">Değişiklikler kaydedildi.</span>}<button type="submit"><Icon name="save"/>Kaydet</button><a href="/" target="_blank" rel="noopener noreferrer"><Icon name="eye"/>Önizle</a></aside>
    </div>
  </form></AdminShell>;
}
